# Generated by Django 4.2.13 on 2024-05-31 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='user')),
                ('location', models.TextField(blank=True, max_length=50, verbose_name='location')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
